version: "3.8"

services:
  telethon-forwarder:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telethon-forwarder
    env_file: .env
    environment:
      - API_ID=${API_ID}
      - API_HASH=${API_HASH}
      - DOWNLOAD_DIR=${DOWNLOAD_DIR:-downloads}
    volumes:
      - ./downloads:/app/downloads
      - ./session:/app/session
    restart: unless-stopped
    stdin_open: true
    tty: true
    # Uncomment untuk production
    # restart: always
    # networks:
    #   - telethon-net

# networks:
#   telethon-net:
#     driver: bridge
